/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package bigsquarekotlin.app

import bigsquarekotlin.utilities.*


fun main() {
    val ary = parseSquare(streamForFile("dat1.txt"))
    val exteriorArray = SquareIntArray(ary.size, IntArray( ary.size * ary.size) { 0 })

    var maxData : MaxData? = null

    for (y in 0 until ary.size) {
        for (x in 0 until ary.size) {
            val newValue = if (ary[y, x]) {
                if (y == 0 || x == 0) {
                    1
                } else {
                    minOf(
                        exteriorArray[y - 1, x], exteriorArray[y, x - 1],
                        exteriorArray[y - 1, x - 1]
                    ) + 1
                }
            } else {
                0
            }
            exteriorArray[y, x] = newValue
            maxData?.value?.let { oldValue ->
                when {
                    newValue == oldValue -> maxData!!.items.add(Coord(y, x))
                    newValue > oldValue -> maxData = MaxData(newValue, mutableListOf(Coord(y, x)))
                    else -> require(newValue < oldValue) { "Invariant violated! newValue=$newValue maxData=$maxData" }
                }
                Unit
            } ?: run {
                maxData = MaxData(newValue, mutableListOf(Coord(y, x)))
            }
        }
    }

    maxData!!.also { (value, items) ->
        for ( data in items) {
            exteriorArray.dump(MaxDatum(value, data))
            println()
            println()
        }
    }
}
