/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package bigsquarekotlin.app

import bigsquarekotlin.utilities.parseSquare
import bigsquarekotlin.utilities.streamForFile

fun main() {
    val ary = parseSquare(streamForFile("dat1.txt"))
    val exteriorArray = IntArray( ary.size * ary.size) { 0 }



}
